# =======================
# environment.yml
# =======================

name: model_circular_proteins
dependencies:
  - python=3.10
  - numpy=2.2.5
  - scipy=1.15.3
  - MDanalysis=2.9
  - pip
  - pip:
      - .
